import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Banner from '../components/Banner'
import Header from '../components/Header'
import MovieBox from '../components/MovieBox'
import { createContext,useState } from 'react'

const inter = Inter({ subsets: ['latin'] })
export const MovieContext = createContext()


export default function Home() {
  const [searchString,setSearchString] = useState("")
  const [movieShow,setMovieShow] = useState(false)
  const [movie,setMovie] = useState([])

  return (
    <>
      <Head>
        <title>Slick Media Test App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
    <MovieContext.Provider value={{searchString,setSearchString,movieShow,setMovieShow,movie,setMovie}}>
      <Header/>
      <Banner/>
      <MovieBox/>
      </MovieContext.Provider>
      </main>
    </>
  )
}
